apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: farmaciaturno
  name: farmaciaturno
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: farmaciaturno
  type: LoadBalancer
status:
  loadBalancer: {}
